### ISSUE TITLE
Install excludes directories without '/' prefix

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#164]
https://github.com/rancher-sandbox/elemental/blob/6fd0d6d61a6a33306cd674c33a62e68df9c29921/pkg/elemental/elemental.go#L342
Implies that the directories considered are located in root (e.g. `/run`, `/mnt`, etc ) however it looks like it's not the case and dirs are passed by as-is down the path, hence it excludes also directories like `/var/run`.

**Comment by davidcassany** [comment]
Interesting, I guess this falls into the scope of rsync usage. We need to explore if adding the root slash (`/`) solves the issue and investigate how grsync maps these options to rsync. There could be some subtle detail to take into account in there.

**Comment by mudler** [comment]
> Interesting, I guess this falls into the scope of rsync usage. We need to explore if adding the root slash (`/`) solves the issue and investigate how grsync maps these options to rsync. There could be some subtle detail to take into account in there.

yes indeed it needs some :eyes: and be verified, I was thinking as well that `/` as prefix might be enough, but some subtle detail might make `/run` map to `/var/run` as well (for example  without specifying explictly that it must start with "`/`", like with regexes instead that would be `^/run`, same applies for every element in that list).

In any case we should at least enhance our suite to cover such scenarios so doesn't happen again.

**Comment by johnliu55tw** [comment]
Seems like [grsync](https://github.com/zloylos/grsync/blob/05aea0d730583a14ae696e7b703f550c9c96e877/rsync.go#L570) passes each string as `--exclude=<string>` argument to the `rsync` command. And according to the man page of rsync, `--exclude=foo` means it will match `foo` anywhere in the tree, which means `run`, `var/run`, and `foo/bar/run` will all be excluded.

> if the pattern starts with a / then it is anchored to a particular spot in the hierarchy of files, otherwise it is matched against the end of the pathname. This is similar to a leading **^** in regular expressions. Thus **/foo** would match a name of "foo" at either the "root of the transfer" (for a global rule) or in the merge-file's directory (for a per-directory rule). An unqualified **foo** would match  a name of "foo" anywhere in the tree because the algorithm is applied recursively from the top down

**Comment by mudler** [comment]
Thanks @johnliu55tw ! good catch by spotting the issue. A fix is on https://github.com/rancher-sandbox/elemental/pull/165 and will follow up to make it available in the repositories
