### ISSUE TITLE
Guess image size from source

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#172]
https://github.com/rancher-sandbox/elemental/blob/80db95e02be93b47372ac25c092c13cc8d228d47/pkg/types/v1/config.go#L80

If we could guess the size of the image needed from the source - either analyzing it or fetching a manifest - we don't need anymore to specify a default image size. 

Also, while we can have a large size here to cover most use cases as we already do, in case where we want to reduce disk footprint usage this is sub-optimal.

**Comment by psviderski** [comment]
Can we at least add support for configuring the image size, e.g. using `DEFAULT_IMAGE_SIZE` variable in `/etc/cos/config` please? At the moment it doesn't seem it is possible to change this 3GB default: https://github.com/rancher/elemental-cli/blob/84c414baf593efee27c2439f3d12a814c9501a85/pkg/constants/constants.go#L60
which is unnecessary too much for my custom Alpine based derivative that has `*.img` size around 200MB and COS_STATE size around 1.5GB.
It would be great to be able to reduce the disk footprint and make `elemental` to support this.

**Comment by davidcassany** [comment]
Yes this is something can think about. I'd say the easiest and robust solution is to prepare the root-tree on a temporary folder and then create the image according to the root-tree size. This would work for any kind of source. The only counter part is having a two step installation, it requires writing the root-tree twice to disk. I'd say this is the way to go and I vote for it, this is a simple refactor as the logic is almost there, we are already doing so for squashfs images.
