### ISSUE TITLE
Reduce build-iso CPU/memory consumption

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#178]
`luet-makeiso` has the capability to set mksquashfs compression options: https://github.com/Luet-lab/luet-makeiso/blob/master/pkg/schema/schema.go#L95

This is particularly helpful in constrained contexts (e.g. running it in a Kubernetes pod) where you could likely hit limits. We need or either control the cpu usage somehow, or simply expose compression options to build-iso like it is in makeiso.

**Comment by kkaempf** [comment]
This is currently blocking ISO builds on ARM. This step used to be ~5 mins (with `makeiso`), now takes > 30mins (haven't run it to the end) on an 8GB RPi4

**Comment by mudler** [comment]
> This is currently blocking ISO builds on ARM. This step used to be ~5 mins (with `makeiso`), now takes > 30mins (haven't run it to the end) on an 8GB RPi4

We are still compatible 100% with `luet-makeiso`, so that can be used in any case on arm platforms. Note that you can carry the build iso process just fine on a x86_64 host also for ARM isos (in fact, our CI runs it on x86_64).

**Comment by kkaempf** [comment]
Not sure about the compatibility, as I had to apply quite some changes to `elemental-image-build` (copied from `ros-image-build`) to get it working with `build-iso`.

**Comment by kkaempf** [comment]
Btw, it only uses 2 of 4 available cores on ARM during squashfs build.

**Comment by kkaempf** [comment]
Finished after ~ 75 minutes
```
DEBU[2022-05-03T12:41:54Z] Applying source /iso/overlay to target /tmp/elemental-iso389158971/rootfs 
INFO[2022-05-03T13:55:37Z] Preparing EFI image...                       
```

**Comment by kkaempf** [comment]
Build 'hangs' also later, last log message is
```
DEBU[2022-05-03T14:00:33Z] Applying source live/grub2-efi-image to target /tmp/elemental-iso389158971/iso 
```

Not clear what's actually going on at this point. But I see `elemental` (again) using 200% CPU.

**Comment by mjura** [comment]
This issue might be related to https://github.com/google/go-containerregistry/issues/627 it seems that go-containerregistry is quite slow

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/elemental/pull/187 was merged with exposes the command to pass to mksquasfs in regards to compression options.

You you can now call elemental as follows:

`elemental build-iso whatever/docker:rootfs -x "YOUR" -x "COMPRESSION" -x "OPTIONS"`

for example:

`elemental build-iso whatever/docker:rootfs -x "-comp" -x "zstd" -x "-Xcompression-level" -x "1"`

or simply to use the defaults for a given compressor:

`elemental build-iso whatever/docker:rootfs -x "-comp" -x "xz"`

Defaults if nothing is given are as follows:

`-comp", "xz", "-Xbcj ARCH`

Where arch depends on the runtime values (i.e. arm if running under arm or x86 if running under x86)

See all possible options here:

```
Compressors available and compressor specific options:
	gzip (default)
	  -Xcompression-level <compression-level>
		<compression-level> should be 1 .. 9 (default 9)
	  -Xwindow-size <window-size>
		<window-size> should be 8 .. 15 (default 15)
	  -Xstrategy strategy1,strategy2,...,strategyN
		Compress using strategy1,strategy2,...,strategyN in turn
		and choose the best compression.
		Available strategies: default, filtered, huffman_only,
		run_length_encoded and fixed
	lzo
	  -Xalgorithm <algorithm>
		Where <algorithm> is one of:
			lzo1x_1
			lzo1x_1_11
			lzo1x_1_12
			lzo1x_1_15
			lzo1x_999 (default)
	  -Xcompression-level <compression-level>
		<compression-level> should be 1 .. 9 (default 8)
		Only applies to lzo1x_999 algorithm
	lz4
	  -Xhc
		Compress using LZ4 High Compression
	xz
	  -Xbcj filter1,filter2,...,filterN
		Compress using filter1,filter2,...,filterN in turn
		(in addition to no filter), and choose the best compression.
		Available filters: x86, arm, armthumb, powerpc, sparc, ia64
	  -Xdict-size <dict-size>
		Use <dict-size> as the XZ dictionary size.  The dictionary size
		can be specified as a percentage of the block size, or as an
		absolute value.  The dictionary size must be less than or equal
		to the block size and 8192 bytes or larger.  It must also be
		storable in the xz header as either 2^n or as 2^n+2^(n+1).
		Example dict-sizes are 75%, 50%, 37.5%, 25%, or 32K, 16K, 8K
		etc.
	zstd
	  -Xcompression-level <compression-level>
		<compression-level> should be 1 .. 22 (default 15)
```


@kkaempf could you try this with different options to see if it works for you?
Alos @agracey I think you wanted this as well?

**Comment by kkaempf** [comment]
I finally came around to give this a try on RPi4. Builds now finish much quicker, about 10-15 mins (down from > 1 hr!)
