### ISSUE TITLE
Disable image verification by default

### ISSUE THREAD

**Issue by mjura** [rancher/elemental-cli#183]
### What is wrong:

After building example image, I tried to install it with command
`elemental --debug install -d ttl.sh/example-mjura:8h /dev/vdb`

as results I have got following stacktrace

```
INFO[2022-05-04T13:59:21Z] Creating file system image /run/cos/state/cOS/active.img 
DEBU[2022-05-04T13:59:21Z] Running cmd: 'mkfs.ext2 -L COS_ACTIVE /run/cos/state/cOS/active.img' 
DEBU[2022-05-04T13:59:21Z] Mounting image COS_ACTIVE                    
DEBU[2022-05-04T13:59:21Z] Running cmd: 'losetup --show -f /run/cos/state/cOS/active.img' 
INFO[2022-05-04T13:59:22Z] Copying COS_ACTIVE image...                  
INFO[2022-05-04T13:59:22Z] Unpacking docker image: ttl.sh/example-mjura:8h 
  ERROR     Plugin luet-mtree at /usr/bin/luet-mtree had an error: error while executing plugin: exit status 1
panic: fatal error

goroutine 104 [running]:
github.com/mudler/luet/pkg/api/core/logger.(*Logger).Fatal(0x40c527, {0xc0318229d0, 0x11801e0, 0xc0014fa501})
	/home/mjura/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/api/core/logger/logger.go:255 +0x47
github.com/mudler/luet/pkg/api/core/bus.(*Bus).Initialize.func1(0xc000262880, 0xc031569380)
	/home/mjura/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/api/core/bus/events.go:108 +0x45d
reflect.Value.call({0x118f6e0, 0xc0000d09f0, 0x13}, {0x13829cb, 0x4}, {0xc0315695f0, 0x2, 0x2})
	/usr/lib64/go/1.17/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x118f6e0, 0xc0000d09f0, 0x41ab00}, {0xc0315695f0, 0x2, 0x2})
	/usr/lib64/go/1.17/src/reflect/value.go:339 +0xc5
github.com/chuckpreslar/emission.(*Emitter).Emit.func1({0x118f6e0, 0xc0000d09f0, 0x0})
	/home/mjura/go/pkg/mod/github.com/chuckpreslar/emission@v0.0.0-20170206194824-a7ddd980baf9/emitter.go:209 +0x439
created by github.com/chuckpreslar/emission.(*Emitter).Emit
	/home/mjura/go/pkg/mod/github.com/chuckpreslar/emission@v0.0.0-20170206194824-a7ddd980baf9/emitter.go:184 +0x2d6
```

### Solution:

To resolve this problem I had to disable image verification

`elemental --debug install --no-verify -d ttl.sh/example-mjura:8h /dev/vdb`

### What should be done:

We should probably disable verification by default, or at least improve the error message, but if you didn't pushed any hash for your image it fails, as tries to check against a mtree

### PR's:

- [x] https://github.com/rancher-sandbox/elemental/pull/208
- [ ] https://github.com/rancher-sandbox/ros-installer/pull/2
- [x] https://github.com/rancher-sandbox/cOS-toolkit/pull/1338

**Comment by Itxaka** [comment]
yes, improving the error message is a must. In fact we rely in luet using the luet-mtree plugin, but we should probably bring the luet-mtree code into elemental somehow so we have control over it instead of relaying in the old way. I think there may be an open issue about that.
