### ISSUE TITLE
Output of spawned commands not visible

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-cli#194]
Running `elemental build-iso` I see in `ps` output that `rsync` got spawned:

```
13324 ?        Ssl   54:17  \_ elemental --debug --config-dir . build-iso
13362 ?        S      0:13      \_ rsync --archive --acls --xattrs --partial --human-readable --progress --exclude=/mnt --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/tmp --exclude=/host --exclude=/run /iso/overlay/ /tmp/elemental-iso619470678/rootfs/
13363 ?        S      0:02          \_ rsync --archive --acls --xattrs --partial --human-readable --progress --exclude=/mnt --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/tmp --exclude=/host --exclude=/run /iso/overlay/ /tmp/elemental-iso619470678/rootfs/
13364 ?        S      0:21              \_ rsync --archive --acls --xattrs --partial --human-readable --progress --exclude=/mnt --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/tmp --exclude=/host --exclude=/run /iso/overlay/ /tmp/elemental-iso619470678/rootfs/
```

rsync is running with `--progress` but there's no visible output although elemental is called with `--debug`

```
Step 15/26 : RUN cd /iso &&     elemental --debug --config-dir . build-iso
 ---> Running in 61b1b8ca4024
INFO[2022-05-10T09:23:22Z] Starting elemental version 0.0.14            
DEBU[2022-05-10T09:23:22Z] Full config loaded: &{ISO:0x400029f0e0 Date:false Name:output RawDisk:map[] OutDir: Config:{Logger:0x400047f7a0 Fs:0x1b21160 Mounter:0x400012f5d8 Runner:0x4000570450 Syscall:0x1b21738 CloudInitRunner:0x400028f650 Luet:0x400013a9b0 Client:0x4000136f70 Cosign:false CosignPubKey: Repos:[] Arch:x86_64 SquashFsCompressionConfig:[]}} 
INFO[2022-05-10T09:23:22Z] Preparing squashfs root...                   
DEBU[2022-05-10T09:23:22Z] Applying source /iso/overlay to target /tmp/elemental-iso619470678/rootfs 
```

**Comment by kkaempf** [comment]
Debugging `rsync` with `strace` reveals the following on `aarch64` (RPi 4)

- rsync is correctly called with `--human-readable --progress`
- `strace` shows the writes to stdout
- there are two writes to stdout:
  ```
  write(1, "\r          3.67K 100%    2.83kB/"..., 46) = 46
  write(1, "\r          3.67K 100%    2.83kB/"..., 76) = 76
  ```
  It's the same string, but different lengths !
- the first write return immediately (looking with `strace -p ...`)
- the second write gets called, but returns only after a delay of 1-2 seconds

All in all it looks as if `elemental` sets up I/O redirection for stdout (+ stderr ?!) but writes get 'stuck' somehow.

**Comment by kkaempf** [comment]
The
> DEBU[2022-05-11T14:27:46Z] Applying source /iso/overlay to target /tmp/elemental-iso237388410/rootfs 

step during `elemental-image-build` on RPi 4 takes > 1 hour !

**Comment by mudler** [comment]
> step during `elemental-image-build` on RPi 4 takes > 1 hour !

This might be alleviated by https://github.com/rancher-sandbox/cOS-toolkit/issues/1003 (if it's not rsync the issue here). indexing might be quite intensive atm for arm

**Comment by kkaempf** [comment]
Just for the record: The same `rsync` run takes like ~10 seconds on x86_64 (vs. more than an hour on aarch64) 🤯

**Comment by kkaempf** [comment]
Slowness is not coming from a slow disk. There's just no I/O happening for most of the time

```
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0      0 4071528 107816 3264224    0    0   178   577 1992  726 14 16 68  2  0
 2  0      0 4071276 107816 3264224    0    0     0     0 16235  275 15 35 50  0  0
 2  0      0 4071112 107816 3264224    0    0     0     0 16236  293 18 32 50  0  0
 2  0      0 4070860 107816 3264224    0    0     0     0 16244  281 19 32 50  0  0

```

**Comment by Itxaka** [comment]
@kkaempf with the latest elemental, now when rsync it will report the states of it (total files, completed, pending, speed) every 5 seconds, as long as there are files left to copy and you have debug enabled. Can you confirm this is what you were looking for?

**Comment by kkaempf** [comment]
Need to reopen since I still don't see progress from rsync :-(

**Comment by kkaempf** [comment]
Oh, I need `--debug` 🤦🏻

**Comment by kkaempf** [comment]
Not sure what the debug output is trying to tell me though:
```
...
DEBU[2022-07-29T11:42:00Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 91.33 / rem. 1023 / tot. 11801 / sp. 3.97kB/s 
DEBU[2022-07-29T11:42:06Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 91.41 / rem. 1017 / tot. 11834 / sp. 498.70kB/s 
DEBU[2022-07-29T11:42:11Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 86.20 / rem. 1740 / tot. 12606 / sp. 2.92MB/s 
DEBU[2022-07-29T11:42:16Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 86.74 / rem. 1672 / tot. 12606 / sp. 40.98MB/s 
DEBU[2022-07-29T11:42:21Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 87.12 / rem. 1624 / tot. 12606 / sp. 2.06MB/s 
DEBU[2022-07-29T11:42:26Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 87.44 / rem. 1583 / tot. 12606 / sp. 19.41kB/s 
DEBU[2022-07-29T11:42:31Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 87.85 / rem. 1532 / tot. 12606 / sp. 0.97kB/s 
DEBU[2022-07-29T11:42:38Z] progress rsync rootfs/ to /tmp/elemental-iso707117351/rootfs/: 88.09 / rem. 1502 / tot. 12606 / sp. 252.44kB/s 
...
```
All values, except for "tot." go up and down without clear direction 🤷🏻

**Comment by Itxaka** [comment]
Remaining files, total files  and speed.

**Comment by kkaempf** [comment]
remaining goes up and down ... 😮

**Comment by Itxaka** [comment]
Yeah makes sense, I think that until rsync enters a dir to sync it it doesn't know how many files there are.

That is why the total also goes up, it finds the files in the fir and adds it to he total.

Maybe rsync has a flag or something to first calculate the total before starting but we would need to sent it against our fork of grsync
