### ISSUE TITLE
Elemental upgrade fails on alpine

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#198]
Seems https://github.com/jaypipes/ghw/issues/133 is hitting us on alpine, preventing upgrades (installation works)
I tried to actually check what's in udev data, and it seems all empty, so ghw is entirely confused by it:

( unknown is my attempt to print out all the partitions labels )
```
INFO[2022-05-10T22:52:30Z] Starting elemental version v0.0.1                                                           
[0xc00034e800 0xc00034e880 0xc00034e900 0xc00034e980]       
unknown
unknown
unknown
unknown
ERRO[2022-05-10T22:52:37Z] Could not find device for COS_RECOVERY label: no device found 
c3os:~$ ps aux | grep udev
root      1407  0.0  0.1   7068  2520 ?        Ss   21:46   0:00 /sbin/udevd
c3os      8435  0.0  0.0   1584   864 pts/0    S+   22:54   0:00 grep udev
c3os:~$ ls -lia^C
c3os:~$ sudo cat /sys/block/sda/sda1/dev
8:1
c3os:~$ sudo GHW_DISABLE_TOOLS=false ./elemental upgrade^C
c3os:~$ ls -liah /run/udev
udev/     udev.pid  
c3os:~$ ls -liah /run/udev/data/
c10:200  c7:130   c7:131   c7:132   c7:133   c7:134   c7:2     c7:3     c7:4     c7:5     c7:6     c7:66    c7:67    c7:68    c7:69    c7:70    n3       
c3os:~$ ls -liah /run/udev/data/
total 0
15127 drwxr-xr-x 2 root root 380 May 10 21:46 .
13052 drwxr-xr-x 6 root root 140 May 10 21:46 ..
23453 -rw-r--r-- 1 root root   0 May 10 21:46 c10:200
23129 -rw-r--r-- 1 root root   0 May 10 21:46 c7:130
23136 -rw-r--r-- 1 root root   0 May 10 21:46 c7:131
23153 -rw-r--r-- 1 root root   0 May 10 21:46 c7:132
23165 -rw-r--r-- 1 root root   0 May 10 21:46 c7:133
23178 -rw-r--r-- 1 root root   0 May 10 21:46 c7:134
23121 -rw-r--r-- 1 root root   0 May 10 21:46 c7:2
23138 -rw-r--r-- 1 root root   0 May 10 21:46 c7:3
23145 -rw-r--r-- 1 root root   0 May 10 21:46 c7:4
23158 -rw-r--r-- 1 root root   0 May 10 21:46 c7:5
23171 -rw-r--r-- 1 root root   0 May 10 21:46 c7:6
23125 -rw-r--r-- 1 root root   0 May 10 21:46 c7:66
23140 -rw-r--r-- 1 root root   0 May 10 21:46 c7:67
23149 -rw-r--r-- 1 root root   0 May 10 21:46 c7:68
23162 -rw-r--r-- 1 root root   0 May 10 21:46 c7:69
23175 -rw-r--r-- 1 root root   0 May 10 21:46 c7:70
23458 -rw-r--r-- 1 root root   0 May 10 21:46 n3
```

### Considered alternative
enable detection with tools: https://github.com/rancher-sandbox/elemental/blob/89d323a36cd0234e462bc189010069b29b323129/pkg/utils/getpartitions.go#L65

**Comment by Itxaka** [comment]
> enable detection with tools: 

Tools wont work here as currently the only thing detected with tools are the UUID of the partition.

@mudler do you have any way I can repro it? i.e. the image being used for that test?

edit: I can see on the bug that its c3os?

**Comment by Itxaka** [comment]
This kind of makes sense imho, systemd is not running on alpine systems so they wont fill the udev database with the proper info, so ghw wont work in that case.

*IF* running on a container thought, you can pass the  /run/udev/data to the container and that should work

**Comment by Itxaka** [comment]
weird, because booting c3os from iso and partitioning the disk I can see the data appear under the /run/udev/data and can query it with udevadm info DEVICE no problem...

**Comment by mudler** [comment]
Any alpine image since the switch to ghw can't upgrade anymore, so for e.g. it is reproducible with this one: https://github.com/c3os-io/c3os/releases/download/v1.23.6-46/c3os-alpine-v1.23.6-46.iso, after install isn't possible to upgrade. Running this inside a container isn't going to work too as the underlying host is alpine.

Note that c3os on alpine does start `eudev`, so there is `udev` running

**Comment by Itxaka** [comment]
udevadm info DEVICE does not show that much info to be honest, this seems to be a thing with alpine, not with ghw. I dont understand why, as booting from iso shows the udevadm filled correctly with new changes 

![image](https://user-images.githubusercontent.com/1447686/167862429-bddbcae6-d784-441c-88a5-361f82c51d11.png)

**Comment by Itxaka** [comment]
its very weird becuase the /dev/disk/by-label is properly filled, so eudev is doing its work with the rules, its just not filling the udev db properly somehow. Maybe its systemd-udev the one that does the dumping of devices to the db and that its not done on eudev?

**Comment by mudler** [comment]
what bugs me even more is - during install isn't the same code being hit to re-detect partitions? how udev would have worked at that stage then?

**Comment by Itxaka** [comment]
> what bugs me even more is - during install isn't the same code being hit to re-detect partitions? how udev would have worked at that stage then?

well, not really no, during install the eudev daemon is running so the partition creation makes the kernel send events of those newly created/modified partitions, so in that case it seems that eudev is creating the data, not sure why. But it doesnt seem to get the data on boot. Maybe the eudev daemon does not go over the existing disks and only reacts to new events?

In upgrade we detect existing partitions, as if those havent generated any events then udev knows nothing about them.

I wonder if I could reproduce this easily by modifying a partition label or something

**Comment by mudler** [comment]
> > what bugs me even more is - during install isn't the same code being hit to re-detect partitions? how udev would have worked at that stage then?
> 
> well, not really no, during install the eudev daemon is running so the partition creation makes the kernel send events of those newly created/modified partitions, so in that case it seems that eudev is creating the data, not sure why. But it doesnt seem to get the data on boot. Maybe the eudev daemon does not go over the existing disks and only reacts to new events?
> 
> In upgrade we detect existing partitions, as if those havent generated any events then udev knows nothing about them.
> 
> I wonder if I could reproduce this easily by modifying a partition label or something

I thought at this too, so my first attempts were trying to get udev to populate things manually and then run upgrade again, but without success:

```
udevadm trigger --attr-match=dev --action=add
udevadm trigger --subsystem-match=net --action=add
udevadm trigger --type=subsystems --action=add
udevadm trigger --type=devices --action=add
```

**Comment by Itxaka** [comment]
ah interesting, if you trigger the `udev-trigger` service, it will fill everything properly. So maybe c3os is missing the service triggering? I would expect that to happen on udev daemon start....

![image](https://user-images.githubusercontent.com/1447686/167869102-3abb1660-3b35-45e3-885f-d8d93d75aad0.png)

**Comment by mudler** [comment]
> ah interesting, if you trigger the `udev-trigger` service, it will fill everything properly. So maybe c3os is missing the service triggering? I would expect that to happen on udev daemon start....
> 
> ![image](https://user-images.githubusercontent.com/1447686/167869102-3abb1660-3b35-45e3-885f-d8d93d75aad0.png)

eeek indeed.. :sweat_smile: good catch!

**Comment by Itxaka** [comment]
> I thought at this too, so my first attempts were trying to get udev to populate things manually and then run upgrade again, but without success:

wait, it didnt work on your case? In mine it filled everything properly plus it updates the data if I change things, i.e. change a label for a partition, while before restarting the udev-trigger service it didnt :eye: :nose: :eye: 


Edit: To be fair it does some mumbo jumbo to trigger everything so maybe you were missing something there.

**Comment by mudler** [comment]
> wait, it didnt work on your case? In mine it filled everything properly plus it updates the data if I change things, i.e. change a label for a partition, while before restarting the udev-trigger service it didnt eye nose eye

It didn't here... I've tried the commands above and re-run c3os upgrade and failed again. But I didn't tried the udev-trigger service, that might be doing the thing

**Comment by Itxaka** [comment]
still wont work thought, something about mounting points, but that could be my own issue :D

**Comment by mudler** [comment]
ok, that seems to do the trick as upgrade tests are passing now (https://github.com/c3os-io/c3os/runs/6392091560?check_suite_focus=true), thanks @Itxaka !. Closing the issue as this is mostly related on the system configuration. Although we could expand the docs pointing out at the udev dependency
