### ISSUE TITLE
Docker image `zypper` stanza is cached

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-cli#201]
Whne building the image, the dependencies that we need are installed with `zypper` but it looks like the layer is being cached, so we will never get any updates.

For example, it seems that we are shipping a leap 15.4 which contains a broken libslirp, which was patched 21 days ago, but our image contains the wrong package.

We should make sure to always invalidate the `zypper in` line so we get the newest packages. Otherwise if we want the exact packages, we should pint the versions exactly, but I dont think we want that

**Comment by Itxaka** [comment]
cc @mudler

**Comment by Itxaka** [comment]
#202 should kind of fix this by invalidating the cache when there is a new commit, so images are always updated to the date of the commit. Then its hte image consumer to make sure they zypper ref && zypper dup, but at least we dont ship really old images.

**Comment by kkaempf** [comment]
Afaik, 15.4 is still under development and not released yet.

**Comment by Itxaka** [comment]
Yeah, I'm not sure wtf did I think about to base the elemental image in 15.4....
