### ISSUE TITLE
Consider using ghw for disks and host information

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#22]
Just a spare idea , maybe we can replace the udevadm/partprobe calls with something native like https://github.com/jaypipes/ghw#block-storage

cc @davidcassany

**Comment by davidcassany** [comment]
> Just a spare idea , maybe we can replace the udevadm/partprobe calls with something native like https://github.com/jaypipes/ghw#block-storage
> 
> cc @davidcassany

Fine with me, as long as it works. I'd suggest to start with the current implementation and move to something native if possible. The challenging part is reacting to partition table changes, udevadm turned to be a good option to wait until the kernel reports new devices.

**Comment by davidcassany** [comment]
I am thinking about if it would make sense to use it to validate partitions when using the `--no-format` installer option. Gonna check if this is an straight forward exercise, if so it can be a good place to start trying this library. Removing `udevadm` from partitioner is scary as race conditions like what harvester reported a month ago could pop up again and they were not really popping up consistently in our tests. I'd love to drop `partprobe` and `udevadm`, but I am just wondering how to do it in safe way so we do not have to turn back to them again 😅 We need to find some playground to experiment with alternatives.

**Comment by Itxaka** [comment]
ghw doesnt seem to be wht we need. It only reads partitions that are mounted, so we cannot use it to find unmounted partitions.

**Comment by mudler** [comment]
I've used it like so to list all available disks (even not mounted ones): 

```golang
	disks := []string{}
	block, err := ghw.Block()
	if err == nil {
		for _, disk := range block.Disks {
			disks = append(disks, fmt.Sprintf("/dev/%s", disk.Name))
		}
	}
```

each Disk has  `Partitions` , but I didn't used it so can't tell if it does what we need

**Comment by Itxaka** [comment]
it reads from the /proc/mounts to get the info on partitions, https://github.com/jaypipes/ghw/blob/main/pkg/block/block_linux.go#L388 so it wont work for our use case. Which I understand, its the simplest and more straightforward way of getting info on partitions, and the point of the lib is to get info that is available now, not what it could do in the future, so it makes sense they only report that.

**Comment by mudler** [comment]
> it reads from the /proc/mounts to get the info on partitions, https://github.com/jaypipes/ghw/blob/main/pkg/block/block_linux.go#L388 so it wont work for our use case. Which I understand, its the simplest and more straightforward way of getting info on partitions, and the point of the lib is to get info that is available now, not what it could do in the future, so it makes sense they only report that.

but that's just used to read the mountpoint if present, no? https://github.com/jaypipes/ghw/blob/fb0598ce62c8057b6aa65122066c93c2042e5ab3/pkg/block/block_linux.go#L197

**Comment by Itxaka** [comment]
And partition type. IIRC ok upgrade we need the partition type of existing FS...not sure why. Maybe we don't need it and can ignore it. Anyway, I tested the lib on my local system and it reported 0 partitions so not sure...

**Comment by Itxaka** [comment]
Umm, on upgrade seems like the existing partitions FS is used to mount it but we may get away by just using "auto" .... gonna have a quick look...

**Comment by Itxaka** [comment]
umm, layout plugin seems to need that partition FS to expand. I wonder if we could do something in there to avoid that somehow, maybe read it from /proc/partitions directly just for that one case

**Comment by Itxaka** [comment]
unfortunately it seems that ghw does not fill the LABEL field for partitions. In fact there is no code in there to do anything with the LABEL so its always empty :/

**Comment by Itxaka** [comment]
I sent a patch upstream to get the label info from the udev database: https://github.com/jaypipes/ghw/pull/304

**Comment by Itxaka** [comment]
sent another to get the partition fs from unmounted partitions https://github.com/jaypipes/ghw/pull/305

Looks like its already got eyes on it, so this might be feasible to do.

**Comment by Itxaka** [comment]
uh...Im gonna guess this is done :D
