### ISSUE TITLE
Generate checksum file after building ISO

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-cli#228]
luet-makeiso had a convenience functionality to generate sha256 checksum files directly after build. 

While this can be easily workarounded after the build process, this was something nice to have to have the build process secured in a homogeneous way.

**Comment by Itxaka** [comment]
+1

Also we could reuse the checksum generated to insert it on packer, so we also verify that the image has the correct checksum as was not borked in the meantime. Im have seen that happen with the packer boxes between CI jobs so its a nice thing to have.
