### ISSUE TITLE
ghw does not fetch partition labels

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-cli#254]
**cos-toolkit version:**

current master version

**CPU architecture, OS, and Version:**

any

**Describe the bug**

There is a regression with the ghw library adoption in elemental, the library does not get the partition label only the filesystem label. The partition name used to be mapped to partition label, now it gets mapped to some device filename. It is not big deal as long as we use default partition labels and as long as we do not relay on the given partition name form the ghw library (I am not 100% sure this is actually the case in current head). The partition names in elemental are constant and human readable (`oem` , `recovery` , `state`,  `efi` , etc.) and partitioner uses that as the partition label.

Not a bug causing issue now, but I bet this can be problematic at some point. The partition label mapped to partition name was done in purpose to provide a canonical way to identify partitions beyond filesystem labels. In code it is not really used because we still support legacy MSDOS partition tables where there are no partition labels at all.

**To Reproduce**

make use of 

**Expected behavior**

The method `utils.GetAllParitions` should map `v1.Partition.Name` to the device partition label if present.

**Additional context**

I found that in the scope of rancher-sandbox/elemental#33 while thinking on how to discover partitions.

**Comment by davidcassany** [comment]
I found udev maps partition labels as `ID_PART_ENTRY_NAME` value and as `PARTNAME`. At least I can see it this way with a `udevadm info --query=all --name=/dev/sdb3`  in my host.

I suspect we could eventually send a PR upstream to include partition labels on partitions analysis. The problem is this is a new field in the partition struct, so I suspect we could be required to find the equivalent for darwin and/or other supported platforms.

**Comment by Itxaka** [comment]
shouldn't this be opened under elemental?

**Comment by Itxaka** [comment]
> I found udev maps partition labels as ID_PART_ENTRY_NAME value and as PARTNAME. At least I can see it this way with a udevadm info --query=all --name=/dev/sdb3 in my host.

On my host, only the ID_PART_ENTRY_NAME is available. PARTNAME is nowhere to be found.

> I suspect we could eventually send a PR upstream to include partition labels on partitions analysis. The problem is this is a new field in the partition struct, so I suspect we could be required to find the equivalent for darwin and/or other supported platforms.

Not really, we could leave that as empty value. Like how UUID works on linux+Macos only :dagger: 

EDIT: actually if you see, on both windows+darwin they transform the actual disk info into a Partition, so it would be as easy as doing it in there with an empty value. Not sure if darwin allows for partition labels....

**Comment by davidcassany** [comment]
I don't think this is a bug **now**, as I'd say there isn't any portion of code using it, as we also consider MSDOS partition tables. Currently a matter of consistency and a potential issue in the future, IIRC in the past there used to be areas where were fetching the partition label as a fallback method.

**Comment by Itxaka** [comment]
https://github.com/jaypipes/ghw/pull/316

**Comment by mudler** [comment]
![Screenshot_linux2020_2022-05-08_00:29:43](https://user-images.githubusercontent.com/2420543/167273954-e8f30c15-17d2-46b7-829c-3298e10446fd.png)
I'm guessing if this could have been causing the following.

Note, this is just doing an elemental upgrade from the active partition ([alpine](https://github.com/c3os-io/c3os/releases/download/v1.23.6-46/c3os-alpine-v1.23.6-46.iso)).

**Comment by Itxaka** [comment]
upstream issue merged, I guess we need to update+change our stuff now :o

**Comment by mudler** [comment]
> ![Screenshot_linux2020_2022-05-08_00:29:43](https://user-images.githubusercontent.com/2420543/167273954-e8f30c15-17d2-46b7-829c-3298e10446fd.png) I'm guessing if this could have been causing the following.
> 
> Note, this is just doing an elemental upgrade from the active partition ([alpine](https://github.com/c3os-io/c3os/releases/download/v1.23.6-46/c3os-alpine-v1.23.6-46.iso)).

I think the issue above is a different one. I'm facing https://github.com/jaypipes/ghw/issues/133 as it seems, I get all unknown labels while printing them out:
```
[0xc00034d280 0xc00034d300 0xc00034d380 0xc00034d400]
unknown
unknown
unknown
unknown
ERRO[2022-05-10T22:42:32Z] Could not find device for COS_RECOVERY label: no device found 

```

Update: opened https://github.com/rancher-sandbox/elemental/issues/198 to track it separately

**Comment by Itxaka** [comment]
as an update, the issue from Ettore ended up being a different thing altogether IIRC.
