### ISSUE TITLE
Log line missing space during "build-iso"

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-cli#303]
Running the `elemental-iso-script` from the `elemental` repo produces log lines in need of an additional space, like

```
Downloadingquay.io/costoolkit/releases-green:repository.yaml
```

**Comment by Itxaka** [comment]
This happens becuase we use logrus directly with `logrus.Infof("hello %s", name)` while luet uses directly params like `luet.Log.Info("hello", name)` and they are joined together, which by default logrus wont do, so we dont get any spaces between the args given in the logger. We may be able to just join stuff with a space somehow....
