### ISSUE TITLE
Partition function cannot create custom/additional partition for installation

### ISSUE THREAD

**Issue by tjjh89017** [rancher/elemental-cli#304]
In past elemental-cli supported create additional partitions.
elemental-cli 0.0.15 didn't have this feature.

Harvester will create a Longhorn partition in the OS disk in some conditions.
So we need to send config to elemental-cli, let it create partition for harvester to use.

Thanks a lot

ref: https://github.com/harvester/harvester/issues/2565

**Comment by Itxaka** [comment]
Thanks for reporting! I'm guessing this was probably lost on the config rework...

@tjjh89017 is this a blocker for harvester? I'm guessing you have it pinned to an older version otherwise this should have appear sooner?

**Comment by tjjh89017** [comment]
I'm trying to upgrade elemental-cli.
I want to confirm if this is a bug or wontfix problem.
I could do some workaround to deal with it.
but if we have official support, I would prefer it.

Currently, it's not a blocker.

Thanks

**Comment by tjjh89017** [comment]
by the way,
Because of this config example, will it be a limitation?
https://github.com/rancher/elemental-cli/blob/main/config.yaml.example#L16

**Comment by Itxaka** [comment]
It may yes, but we probably can introduce a `Custom` or `Extra` key in there to allow for random extra partitions to be added on install.

**Comment by tjjh89017** [comment]
@Itxaka 
Do we have schedule to merge #306 feature?
I'm starting to work on this in harvester side.
