### ISSUE TITLE
Failed preparing ISO's root tree: exit status 5 for v5.2

### ISSUE THREAD

**Issue by divyashukla25** [rancher/elemental-cli#325]
Hi,

Getting "Failed preparing ISO's root tree: exit status 5" for elemental version 5.2. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/112463911/191672431-7edb64b3-868f-4860-9aac-4897570cbcbb.png)

Please fix this.

**Comment by Itxaka** [comment]
Hi @divyashukla25 !

Please update your repo to the latest version. Elemental-cli now uses a new method to configure the grub bootloader and versions <= 5.2 are not compatible. The latest branch in elemental now points to 5.3 which provided the required packages to build the iso image.

Thanks!

**Comment by divyashukla25** [comment]
Sure, Thanks!
