### ISSUE TITLE
If more than one partition has a COS_* label, the grub content would be wrong after upgrade

### ISSUE THREAD

**Issue by Vicente-Cheng** [rancher/elemental-cli#356]
related issues: #348 

With previous fix for harvester, it could upgrade successfully with multiple disks that contain the OCS_* label.
We found that the grub content is not correct after upgrade (checking the file `grub_oem_env`).
That is caused by the same issue on #348 described.

We need to fix that for the tag `v0.0.14-harvester1`.

cc @bk201

**Comment by Itxaka** [comment]
Patch merged and tag updated, new release triggered, available at https://github.com/rancher/elemental-cli/releases/tag/v0.0.14-harvester1

**Comment by Vicente-Cheng** [comment]
@Itxaka, thanks for your help!!
