### ISSUE TITLE
Create default grub files

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-cli#372]
During boot grub trying to search and load several files in order to configure the grub config with override, default values, extra entries etc...

Usually this is not an issue if the files dont exist, but it seems that on some Dell FWs, this causes grub to hang for 30 minutes searching for those files.

We can do better and create those files if they dont exists so grub can find them always, even if they are empty.

Files that grub tries to find:
 - /grubenv
 - /grub_oem_env
 - /grubmenu
 - /grubcustom

**Comment by Itxaka** [comment]
Blocked until the discussion on what to do witht he grub files is concluded: https://github.com/rancher/elemental-toolkit/discussions/1647

**Comment by kkaempf** [comment]
Closing for good - will be tackled with a different PR.
