### ISSUE TITLE
Duplicate "default" in help output for "install"

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-cli#385]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Run
```
elemental install -h
```
outputs
```
...
Global Flags:
      --config-dir string   Set config dir (default is /etc/elemental) (default "/etc/elemental")
...
```

(note the duplication of "default")

**What did you expect to happen:**

```
...
Global Flags:
      --config-dir string   Set config dir (default is "/etc/elemental")
...
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Elemental-cli version 0.0.15+g605346d

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by frelon** [comment]
After https://github.com/rancher/elemental-cli/pull/382 the default is to check current directory first and then _/etc/elemental_ but any mention of a default is removed from the help-text.
