### ISSUE TITLE
`elemental upgrade` fails to remount/umount the RW state partition to RO after the upgrade is done

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-cli#431]
I noted sometimes the `elemental upgrade ...` call fails just at the cleanup phase (upgrade is done and it just fails to umount/remount state partition, busy device error).

This is a tricky place to fail as then the upgrade is not considered to be applied, but in fact it is already done and the active and passive images are there already updated, hence if the upgrade is retriggered automatically it will apply it again moving the updated active to passive again, hence the old and actually functional OS will be lost.

I noted this behavior sporadically in upgrades executed from rancher and elemental-operator.

**Comment by frelon** [comment]
Looks similar to this old issue: https://github.com/rancher/elemental-toolkit/issues/1524

**Comment by davidcassany** [comment]
Indeed, I have a feeling this might be an sporadic race issue of trying to umount too quickly... as I haven't seen it in consistent basis. I was wondering if it would make sense having some sort of umount retry logic, like try to umount at least N times with one second of sleep in between before actually failing.

**Comment by davidcassany** [comment]
Closing as I believe this got fixed in rancher/elemental-toolkit#1736
