### ISSUE TITLE
Incorrect image is pulled when referencing a multi-arch manifest

### ISSUE THREAD

**Issue by jtcressy** [rancher/elemental-cli#452]
Elemental CLI should use the context of the host machine's CPU architecture when pulling an image for upgrade or install. 

Instead, elemental-cli is defaulting to the first or perhaps the linux/amd64 image listed in the manifest and is not guaranteed to match the target system.

This limitation forces derivatives to split images into separate repositories within a container registry and is arguably more messy to maintain.

From a UX perspective, the consumer of a derivative should be able to call `elemental upgrade --system.uri=docker:myimage:latest` without worrying about whether they selected the correct architecture for the machine they are on.

For use-cases outside upgrade or install, the arch should be override-able to support building cloud images for ARM64 instances from an AMD64 builder or vice-versa. (although it's possible that install hooks may fail in this scenario so emulation/virtualization may be necessary anyway)

---

Screenshot Example
<img width="1140" alt="failed elemental upgrade due to exec format error" src="https://user-images.githubusercontent.com/7663028/223589529-2fd972d9-041c-4898-a666-768d76bad07e.png">

An exec format error is shown when after-upgrade hooks are attempted, because elemental cli pulled an amd64 image on an arm64 host.

---

P.S. I'm working on a derivative project that produces multi-arch image tags, but my images are not yet stable. So if anyone would like to reproduce this bug, you can try pulling one of my images but it's not guaranteed to leave you with a functioning system. (https://github.com/jtcressy-home/edgenode/pkgs/container/edgenode)

**Comment by frelon** [comment]
Hi @jtcressy 

Great writeup! As you have spotted our multi-arch support is lacking and the workaround is to use different registries or labels for each platform.

This is definitely on our todo list though!

**Comment by jtcressy** [comment]
@frelon 
> Great writeup! As you have spotted our multi-arch support is lacking and the workaround is to use different registries or labels for each platform.

Thank you!! I've been following along very closely with the improvements being made to elemental toolkit, especially around ARM64 support and it has come a LONG way. You guys are doing great work! Love this project a lot.

**Comment by jtcressy** [comment]
I've identified a good place to implement support for other platforms during upgrade/install/reset. 

https://github.com/rancher/elemental-cli/blob/147779dbcd9191c30d2050cf4652256927b17ba3/pkg/luet/luet.go#L183

If luet could implement a `platform` argument in the `DownloadAndExtractDockerImage`, we could support an optional `--platform` or `--arch` CLI argument and implement some extra logic to detect the host platform to populate a default value.

I've opened an issue over there at mudler/luet#333 to start a conversation around this.

**Comment by kkaempf** [comment]
part of rancher/elemental-toolkit#1738

**Comment by jtcressy** [comment]
@frelon Do your changes in #478 cover the `upgrade` command? I noticed the change to `build-iso` and `install` but didn't see anything for `upgrade` specifically. It's not explicitly necessary to support the `--platform` flag for `upgrade` but it does need to default to `runtime.GOOS/runtime.GOARCH` so that running upgrade on a linux/arm64 machine results in the linux/arm64 image being pulled.

**Comment by frelon** [comment]
> @frelon Do your changes in #478 cover the `upgrade` command? I noticed the change to `build-iso` and `install` but didn't see anything for `upgrade` specifically. It's not explicitly necessary to support the `--platform` flag for `upgrade` but it does need to default to `runtime.GOOS/runtime.GOARCH` so that running upgrade on a linux/arm64 machine results in the linux/arm64 image being pulled.

@jtcressy Yes, the platform will default to the currently running one in upgrade command. 

I did try to think of a reason to add the platform flag to upgrade, but it would probably only be useful in very niche situations.

That being said if you have use of the flag please let us know and we will add it! 👍
