### ISSUE TITLE
Create a device parsing library/package

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-cli#58]
Related to #22 and #57. Would be nice considering some package in elemental to handle device discovery. This is mostly all the logic to find device paths by some of its attributes (filesystem label, partition label, partition number, etc.) in dynamic environments (just right after formatting or partition creation).

**Comment by Itxaka** [comment]
Did this get covered by using ghw? or is it something that we are still missing @davidcassany ?

**Comment by davidcassany** [comment]
Yes I think this should have been closed by https://github.com/rancher/elemental-cli/pull/155
