### ISSUE TITLE
Investigate a FS aware rsync lib

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-cli#70]
Current rsync golang lib just works directly on the real FS. This proves difficult for testing and dangerous as ti affects the current FS of whoever is running the test suite. 

There seems to be no plans to introduce something like that in the current rsync lib in use

We should either find something different that works on a give FS or understand hwo much work would it take to make the lib FS aware.

### Requirements

 - [ ] Check any other libs that do rsync/copy like rsync (xattrs included!)
 - [ ] Check the possibility of contributing upstream to support our use case
 - [ ] Check the possibility of creating our own forked from upstream to support our use case

**Comment by mudler** [comment]
I guess we can close this one, as the FS refactor in #125  makes our wrapper around grsync FS-aware? https://github.com/rancher-sandbox/elemental/blob/fcf585864a4a239686c72b58dcedd5945215edd3/pkg/utils/common.go#L130
