### ISSUE TITLE
Move flags validaton to some generic place (`cmd/flags.go`?)

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-cli#79]
This to avoid having to duplicate flags checks incompatibilities like `--reboot` and `--poweroff` in all subcommands and reuse the logic.

In addition we could align which flags should be set from env_variables, config files and command line. For instance `--reboot` and `--poweroff` do not make much sense from a config file.

See https://github.com/rancher-sandbox/elemental/pull/72#discussion_r799453623

**Comment by Itxaka** [comment]
:+1: we could also have group of flags in there so we can add them as a whole to different subcommands and they are grouped

i.e.

```
func addCosignFlags(cmd *cobra.Command) {
	cmd.Flags().BoolP("cosign", "", false, "Enable cosign verification (requires images with signatures)")
    cmd.Flags().StringP("cosign-key", "", "", "Sets the URL of the public key to be used by cosign validation")
}
```
