### ISSUE TITLE
Move configuration logic to a meaningful package

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-cli#80]
This about discussing and agreeing to a good place to include configuration initialization logic. This is a mixture of runtime loaded configuration and flags in addition to current state status (booted image, installation media, etc.), hence it requires some state logic which is hard to include into `pkg/types/v1/config.go` as it easily results in to circular dependencies between packages as we might need few utilities to run state check which in turn require `v1` package.

As in #72 this logic is placed in `pkg/action` as stand alone methods. There could be some better approach.

**Comment by Itxaka** [comment]
Isnt this kind of done @davidcassany ?

**Comment by davidcassany** [comment]
yes, this is solved. I guess I forgot to link it with #111, as this was just required and needed there.
